### ISSUE TITLE
Add licence!

### ISSUE THREAD

**Issue by skyem123** [Nightfall/Instrumentality#2]
I know this sounds silly, but it's very important to add a licence to the code quickly.

**Comment by ghost** [comment]
Actually this is in the TODO list, we should definitely agree on something

**Comment by skyem123** [comment]
I sugest BSD 2-clause, but MIT is okay as well.

**Comment by ghost** [comment]
@Victorious3 should probably be part of this discussion

**Comment by ghost** [comment]
BSD 2-clause it is (see IRC), though I want to see Vic put agreement on this issue just to be sure

**Comment by Victorious3** [comment]
Yes, go ahead. I agree.
